# SPDX-FileCopyrightText: 2025 reactor_file contributors <https://github.com/ash-project/reactor_file/graphs.contributors>
#
# SPDX-License-Identifier: MIT

# Used by "mix format"
spark_locals_without_parens = [
  chardata: 1,
  chgrp: 1,
  chgrp: 2,
  chmod: 1,
  chmod: 2,
  chown: 1,
  chown: 2,
  close_file: 1,
  close_file: 2,
  content: 1,
  cp: 1,
  cp: 2,
  cp_r: 1,
  cp_r: 2,
  description: 1,
  device: 1,
  existing: 1,
  gid: 1,
  glob: 1,
  glob: 2,
  guard: 1,
  guard: 2,
  io_binread: 1,
  io_binread: 2,
  io_binstream: 1,
  io_binstream: 2,
  io_read: 1,
  io_read: 2,
  io_stream: 1,
  io_stream: 2,
  io_write: 1,
  io_write: 2,
  line_or_bytes: 1,
  line_or_chars: 1,
  line_or_codepoints: 1,
  ln: 1,
  ln: 2,
  ln_s: 1,
  ln_s: 2,
  lstat: 1,
  lstat: 2,
  match_dot: 1,
  mkdir: 1,
  mkdir: 2,
  mkdir_p: 1,
  mkdir_p: 2,
  mode: 1,
  modes: 1,
  new: 1,
  open_file: 1,
  open_file: 2,
  overwrite?: 1,
  path: 1,
  pattern: 1,
  read_file: 1,
  read_file: 2,
  read_link: 1,
  read_link: 2,
  revert_on_undo?: 1,
  rm: 1,
  rm: 2,
  rmdir: 1,
  rmdir: 2,
  source: 1,
  stat: 1,
  stat: 2,
  target: 1,
  time: 1,
  touch: 1,
  touch: 2,
  uid: 1,
  wait_for: 1,
  wait_for: 2,
  where: 1,
  where: 2,
  write_file: 1,
  write_file: 2,
  write_stat: 1,
  write_stat: 2
]

[
  import_deps: [:reactor, :spark],
  inputs: ["{mix,.formatter}.exs", "{config,lib,test}/**/*.{ex,exs}"],
  plugins: [Spark.Formatter],
  locals_without_parens: spark_locals_without_parens,
  export: [
    locals_without_parens: spark_locals_without_parens
  ]
]
